//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPI2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asistencia
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dni { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string consulta { get; set; }
        public bool esCliente { get; set; }
        public Nullable<int> id_modelo { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public string modelo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ModeloProducto ModeloProducto { get; set; }
    }
}
